---
title: "About this blog"
description: A description of the blog
date: '2022-03-12'
menu: main
output: 
md_document:
variant: markdown
---

```{r pressure, echo=FALSE}
library(cowplot)
library(ggplot2)

p1 <- ggdraw() + draw_image("../static/images/IMG_0088.JPG", scale = 0.9)
p2 <- ggdraw() + draw_image("../static/images/IMG_0056.JPG", scale = 0.9)
p3 <- ggdraw() + draw_image("../static/images/IMG_0017.JPG", scale = 0.9)


plot_grid(p1, p2, p3, nrow = 1)
```

My name is Pierre Barban. Freshly graduated from two masters' mainly focusing on environmental economics, I am currently a data analyst at Eco-Counter in Montréal, Canada. My amazing job gives me the opportunity to support cities, national parks, and other governmental institutions to enhance their pedestrian and bicycle counts data.
At the moment I am creating this blog, I intent to share stories mostly covering sustainable topics supported by data analysis. I am also planning on analyzing interesting data sets that I might come upon in my daily life. At the border of academics and story-telling, I hope to write comprehensive posts with the scientific rigour that I have learned throughout my young research career. Unless specified, all my data analysis are down with the programming language R. All constructive feedback are more than welcome. 



